### ISSUE TITLE
enter key on number pad not working

### ISSUE THREAD

**Issue by CorpHackRyan** [patpragman/pat_notes#1]
I can use the enter key on the regular keyboard, but when I try to use it on my number pad nothing happens

**Comment by patpragman** [comment]
I'm not sure why that is at all.  Maybe tkinter doesn't support the enter button over there?  Since I bought my new computer the number pad doesn't work at all.

**Comment by patpragman** [comment]
I don't think there's much one could do about this - this is a function of whatever OS one is using, I didn't really do anything with keybindings...
